juan
menendezjaume/musical-disco pull request #16
Opened 2024-04-11 14:46 UTC by JuanSebastianPerniola

2024-04-11 15:14 UTC, menendezjaume commented
@JuanSebastianPerniola, si añades el juego como submódulo, tienes que crear un fichero `.gitmodules` en la raíz, y referenciar tu repositorio. Algo así:

```
[submodule "16_PyPlanetDefender"]
	path = 16_PyPlanetDefender
	url = https://github.com/JuanSebastianPerniola/PyGame.git
```

De lo contrario, la carpeta estará vacía. Aquí tienes la documentación https://git-scm.com/book/en/v2/Git-Tools-Submodules

Si no quieres usar submódulos, tendrás que añadir todos los ficheros que compongan el juego.

2024-04-11 15:33 UTC, menendezjaume requested changes
Lo dicho.

2024-04-16 18:59 UTC, JuanSebastianPerniola commented
he arreglado los cambios pedidos,  y estan subidos, creo otra pull request

2024-04-17 13:14 UTC, menendezjaume requested changes
Cuando termina la partida, recibo este error:
```
Traceback (most recent call last):
  File "/home/micky/cide/musical-disco/16_PlanetDefender/Main.py", line 250, in <module>
    menu.mainloop(pantalla)
  File "/home/micky/.local/lib/python3.10/site-packages/pygame_menu/menu.py", line 3027, in mainloop
    self.update(pygame.event.get())
  File "/home/micky/.local/lib/python3.10/site-packages/pygame_menu/menu.py", line 2566, in update
    selected_widget.update_menu(events)
  File "/home/micky/.local/lib/python3.10/site-packages/pygame_menu/widgets/core/widget.py", line 2762, in update_menu
    return self.update(events)
  File "/home/micky/.local/lib/python3.10/site-packages/pygame_menu/widgets/widget/button.py", line 211, in update
    self.apply()
  File "/home/micky/.local/lib/python3.10/site-packages/pygame_menu/widgets/core/widget.py", line 1263, in apply
    return self._onreturn(*args, **self._kwargs)
  File "/home/micky/cide/musical-disco/16_PlanetDefender/Main.py", line 206, in start_the_game
    texto_game_over = pygame.image.load("gameover.png")
FileNotFoundError: No file 'gameover.png' found in working directory '/home/micky/cide/musical-disco/16_PlanetDefender'.
```

Creo que la razón es porque el fichero tiene la O mayúscula, pero en la referencia en el código, línea 206 del Main, está en minúscula.

2024-04-21 17:25 UTC, JuanSebastianPerniola commented
He estado haciendo pruebas, me podrias confirmar desde donde inicias la partida?
En local tampoco me iba pero era por que estaba intentando iniciar el proyecto desde fuera.
Aunque me daba otro error

2024-04-22 09:28 UTC, menendezjaume commented on 16_PlanetDefender/Main.py
> +                    texto_game_over = pygame.image.load("gameover.png")
La inicio desde la carpeta del juego (./16_PlanetDefender). El problema es que Windows no es case-sensitive, y Linux sí. Como arreglarlo para Linux no lo estropea para Windows, creo que deberíamos poner la ruta con el mismo nombre que el fichero (que además es lo correcto).

Aquí, hay que cambiar `gameover.png` por `gameOver.png`.

2024-04-22 18:30 UTC, JuanSebastianPerniola commented on 16_PlanetDefender/Main.py
> +                    texto_game_over = pygame.image.load("gameover.png")
okey

2024-04-22 18:34 UTC, JuanSebastianPerniola commented on 16_PlanetDefender/Main.py
> +                    texto_game_over = pygame.image.load("gameover.png")
cambios efectuados

2024-04-23 13:00 UTC, menendezjaume approved these changes

2024-04-23 13:00 UTC, merged